version: '3'

networks:
    gateway:
        external: true

services:
  politics:
    container_name: politics
    build:
      dockerfile: Dockerfile
    labels:
        - traefik.enable=true
        - traefik.http.routers.politics.rule=Host(`polinsight.xyz`)
        - traefik.http.services.politics.loadbalancer.server.port=3000
        - traefik.http.routers.politics.tls=true
        - traefik.http.routers.politics.tls.certresolver=letsencrypt
    networks:
        - gateway
    restart: always