version: '3'
services:
  myapp:
    container_name: AmericaPolitics
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: AmericaPoliticsNginx
    volumes:
      - ./visual/web:/usr/share/nginx/html
    ports:
      - "8080:80"

  politics-web:
    container_name: politics-web
    environment:
        - TZ=Asia/Shanghai
    labels:
        - traefik.enable=true
        - traefik.http.routers.politics-web.rule=Host(`polinsight.xyz`)
        - traefik.http.services.politics-web.loadbalancer.server.port=8080
        - traefik.http.routers.politics-web.tls=true
        - traefik.http.routers.politics-web.tls.certresolver=letsencrypt
    privileged: true
    stdin_open: true
    tty: true
    networks:
        - gateway
    restart: always